# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "centos" do |centos|
    centos.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    centos.vm.hostname = "centos"
    centos.vm.box = "chef/centos-7.0"
    centos.vm.network "private_network", ip: "192.168.50.4"
    centos.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = './vagrant_ansible_inventory_static'
      ansible.limit = '192.168.50.4'
      ansible.verbose = 'vvv'
    end
  end
  config.vm.define "centos2" do |centos2|
    centos2.vm.hostname = "centos2"
    centos2.vm.box = "chef/centos-7.0"
    centos2.vm.network "private_network", ip: "192.168.50.5"
    centos2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = './vagrant_ansible_inventory_static'
      ansible.limit = '192.168.50.5'
      ansible.verbose = 'vvv'
    end
  end
  config.vm.define "centos3" do |centos3|
    centos3.vm.hostname = "centos3"
    centos3.vm.box = "chef/centos-7.0"
    centos3.vm.network "private_network", ip: "192.168.50.6"
    centos3.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = './vagrant_ansible_inventory_static'
      ansible.limit = '192.168.50.6'
      ansible.verbose = 'vvv'
    end
  end
end
